spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: ange
    password: 123456
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8443
  ssl:
    key-store: file:src/main/resources/mykeys.jks
    key-store-password: dragon
    key-password: dragon