spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: ange
    password: 123456
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
server:
  port: 8080


