spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: ange
    password: 123456
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /data-api
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:9000/oauth2/jwks
server:
  port: 8080

